<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GuiShark.OpenGL/GuiShark.OpenGL.csproj" />
    <PackageReference Include="OpenTK.Windowing.Desktop" Version="4.9.4" />
    <Content Include="Assets/**/*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../GuiShark.Demo/Assets/fonts/**/*" Link="Assets/fonts/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
