<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../hosting/GuiShark.ProcessHosting/GuiShark.ProcessHosting.csproj" />
    <PackageReference Include="OpenTK.Windowing.Desktop" Version="4.9.4" />
    <Content Include="Assets/**/*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../GuiShark.Demo/Assets/fonts/Lato-Regular.ttf" Link="Assets/fonts/Lato-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../GuiShark.Demo/Assets/fonts/Lato-Bold.ttf" Link="Assets/fonts/Lato-Bold.ttf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
