<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>OpenGL 3.3 renderer for GuiShark.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GuiShark/GuiShark.csproj" />
    <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
    <PackageReference Include="SkiaSharp" Version="4.153.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.153.0" />
  </ItemGroup>
</Project>

