<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../GuiShark.OpenGL/GuiShark.OpenGL.csproj" />
    <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
    <Content Include="../SharedAssets/fonts/**/*" Link="Assets/fonts/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../licenses/SDL-zlib.txt" Link="licenses/SDL-zlib.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets/**/*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../GuiShark.Demo/Assets/fonts/*" Link="Assets/fonts/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="../GuiShark.Demo/FrameCapture.cs" Link="FrameCapture.cs" />
  </ItemGroup>
</Project>
